name: Ejemplo de Composite Action

on: [push]

jobs:
    global-Variables:
        runs-on: ubuntu-latest
      
        env:
          MY_VAR: Mi variable de entorno

        steps:
          - name: Test
            env:
              STEP_MY_VAR: Hola estoy en el paso
            run: echo "Hola Mundo " $MY_VAR $STEP_MY_VAR