name: "My action"
description: "My action description"
author: "Fernando"

inputs:
  message:
    description: "My input description"
    required: true
    default: "Katherine"

runs: 
  using: "composite"

  steps:
    - name: Saludo
      run: echo "Hola ${{ inputs.message }}"
      shell: bash