name: Ejemplo de Composite Action

on: [push]

jobs:
    global-Variables:
        runs-on: ubuntu-latest
      
        env:
          MY_VAR: Mi variable de entorno

        steps:
          - name: Test
            run: echo "Hola Mundo  ${{ vars.MY_VARIABLE2 }}"

            
          - name: Secret
            run: echo "Hola Mundo  ${{ secrets.MY_SECRET }}"