name: Hola Mundo

on: #[push, pull_request] --Estos eventos se ejecutan en cada push o pull request
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    hola: 
        runs-on: ubuntu-latest
        steps:
            - name: Saludo
              run: echo "Hola Mundo"
            - name: touch file
              run: touch file.txt
            - name: Set text
              run: echo "Hola Mundo" > file.txt
            - name: cat file
              run: cat file.txt

    other:
        runs-on: ubuntu-latest
        needs: hola
        steps:
            #Tomado de marketplace de github actions
            - name: Checkout
              uses: actions/checkout@v4.2.2
            - name: LS
              run: ls -al